---
- name: setup service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - { src: "service.j2", dest: "/etc/systemd/system/vpn-script-daemon.service" }

- name: get binary
  get_url:
    url: "{{ service_binary_url }}"
    dest: /root/vpn-script-daemon
    mode: 0755

#- name: start service
#  service:
#    name: vpn-script-daemon
#    state: started
#    enabled: no
